# Generated by Django 4.1.1 on 2022-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='comm',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
